### PR TITLE
added `image_histogram`

### PR DESCRIPTION
**Pull request by romainfrancois**
this adds the function `image_histogram` to compute that kind of histograms: 

capture d ecran 2016-10-31 a 15 24 04

It returns a new image with the 4 histograms (r, g, b and the gray one which is just the average of the other 3). 

I've used `tbb` from `RcppParallel` to achieve some obvious parallelisation. 

Let me know if you feel this should be in some other package instead. 

Based on this http://www.la-photo-en-faits.com/2013/11/histogramme-photo-luminosite-rvb.html?m=1

### CODE REVIEW

**Comment by jeroenooms** [comment]
Are you not using the ImageMagick native histogram functions? See [STL docs](https://www.imagemagick.org/Magick++/STL.html) **Obtaining A Color Histogram**

**Comment by romainfrancois** [comment]
ah yes, that would have been easier. I'll have a look. Thanks.

**Comment by romainfrancois** [comment]
From what I could find, this gives me a way to count the colors with something like this

```
// [[Rcpp::export]]
void magick_image_colorHistogram( XPtrImage image ){
  std::vector<std::pair<Magick::Color,unsigned long> > histogram;
  Magick::colorHistogram( &histogram, image->front() );
  // post process histogram
}
```

That's the easy part, and that's quite slow: 

```
> image_info(im)
  format width height colorspace filesize
1   JPEG  1440   1920       sRGB   207383
> system.time( magick_image_colorHistogram(im) )
   user  system elapsed 
  0.331   0.010   0.341 
```

As a comparison, the function not using `colorHistogram` and actually making the image histogram : 

```
> system.time( image_histogram(im) )
   user  system elapsed 
  0.024   0.011   0.035 
```

I would also have to figure out a way to go from the `std::vector<std::pair<Magick::Color,unsigned long> >` to a graphical representation. I did not find this yet.

**Comment by romainfrancois** [comment]
I pushed some code in the `collage` package. Closing this here.

**Comment by jeroen** [comment]
Sorry for dropping the ball, I plan to work on magick again soon.

**Comment by romainfrancois** [comment]
No trouble.

**Comment by jeroen** [comment]
Hope Tigrou is not upset.

**Comment by romainfrancois** [comment]
he's ok, he's now getting `ggplot2` histograms for his images and lots of love in [collage](https://github.com/ThinkRstat/collage)

capture d ecran 2017-07-10 a 19 46 16

**Comment by jeroen** [comment]
Wow that's very cool. Is there performance overhead because you are accessing the bitmap via R instead of the `XPtrImage` object? Or does it work this well as a separate package?

**Comment by romainfrancois** [comment]
Sure `profvis` says most of the time is spent extracting the bitmap indeed.  

capture d ecran 2017-07-10 a 23 06 38

but that's fast enough I guess. 

And avoiding the copies of `magick_image_write_frame` means I'd have to link against the magic libs, etc ... I'd rather leave that to the `magick` 📦 

You could use the range based constructor for `RawVector` : 

```
// Rcpp::RawVector res(output.length());
// memcpy(res.begin(), output.data(), output.length());
Rcpp::RawVector res( output.data() , output.data() + output.length() );
```

But perhaps also first allocate the `RawVector` to the right size, without init with `no_init` and then use `Blob:: updateNoCopy` so that `write` writes directly on the raw vector. 

```
int n = {{ something here that gets the right length}} ;
Rcpp::RawVector res(n) ;
Magick::Blob output ;
output.updateNoCopy( res.begin(), n ) ;
input->front().write(&output, format, 8L);
```

but not sure it's worth the trouble ...

**Comment by jeroen** [comment]
Yes it would be nice if we can keep the magic inside the magick package but still provide the bitmap in an efficient way to other packages.

**Comment by romainfrancois** [comment]
or maybe just use this version of `write` (so skipping Blob) : 

capture d ecran 2017-07-10 a 23 31 09

that's one less copy. Not sure you can access and expose directly the memory of the `Image` object, and having it for sure in the rgba format was easy for me to reason with.

**Comment by jeroen** [comment]
Exposing the memory ptr from  if the `Image` is probably not a good idea because it will be free'd when the R object is cleaned by the GC and then you might 💣. I'll see if we can optimize the conversion to rgba at least...

**Comment by romainfrancois** [comment]
Yep, seeing enough of these already when I rebuild the 📦 

```
Error in magick_image_length(x) : external pointer is not valid
Error in magick_image_length(x) : external pointer is not valid
```

But yeah one copy is better than 2. Maybe I'll play with this too :-)

**Comment by jeroen** [comment]
Without having looked at this, I guess the expensive part is not copying memory but rather parsing the png/jpeg/whatever format...

**Comment by romainfrancois** [comment]
you mean converting from what `Image` is using internally ?  Probably yes, but free is always cheaper than cheap

**Comment by jeroen** [comment]
Hmm I tried something like below but it keeps segfaulting. I'm probably not doing it right. Anyway I think the `memcpy()` is not the bottle neck here, not sure it's worth it.

```cpp
// [[Rcpp::export]]
Rcpp::RawVector magick_image_write_frame(XPtrImage input, const char * format){
  if(input->size() < 1)
    throw std::runtime_error("Image must have at least 1 frame to write a bitmap");
  Magick::Geometry geom = input->front().size();
  size_t len = strlen(format) * geom.width() * geom.height();
  Rcpp::RawVector res(len);
  Magick::Blob * output = new Magick::Blob();
  output->updateNoCopy(res.begin(), len);
  input->front().write(output, format, 8L);
  return res;
}
```

**Comment by romainfrancois** [comment]
That looks fine, but I don't know how write works, nevermind then.

**Pull request closed without merging**
