### PR TITLE
Added blob extraction and segmentation

### PR DESCRIPTION
**Pull request by jwijffels**
I've added image_connect, image_split, image_fuzzycmeans for basic image segmentation and blob extraction as well as as.integer for an image-magick object.  
These functions are linked to image thresholding

### CODE REVIEW

**Comment by jwijffels** [comment]
Hmm, seems to fail on non-windows which has apparently ImageMagick 6.7.7-10 while on Windows which I used to develop this is 6.9.9.4.
I'll fix first.
For the record. I'm also have included functionalities for morphology operations and fx. Do you prefer to have this in 1 pull request or several small ones?

**Comment by jeroen** [comment]
Thanks, I am working on a few others things right now so I have not yet time to review this. In general, smaller pull requests are better.

**Comment by jeroen** [comment]
Some small comments:

I don't think adding the `as.integer.magick-image()` is a good idea, because R uses another integer based format internally for images (the one you get with `dev.capture(native = TRUE)`. I think this may cause confusion when users assume that `as.integer()` will give them that format. So better remote that I think.

Do I understand it correctly that `image_split()` simply returns `n` black-white images, one for each unique color in the input image? We can probably implement that much more efficiently in C++.

**Comment by jwijffels** [comment]
Yes, image_split does that. Connectedcomponents returns the same valse for all pixels which are next to each other and are the same or almost the same. Image _split then gets each of these blobs. This is a basic technique to count objects: use morphology operations (dilating/eroding) to smooth the image, connect the pixel intensities with connectedcomponents, next count or do something else like seeing how large each blob is

**Comment by jeroen** [comment]
By the way I think instead of `names(table(pixels))` you mean to do `unique(pixels)`.

**Comment by jwijffels** [comment]
Yes. Don't remember why I did this. unique will be better.

**Comment by jeroen** [comment]
I have rewritten this a bit and merged via https://github.com/ropensci/magick/commit/436721a9a47bc7686e413abd52b17a7b52556365. Thanks for your contributions !

**Comment by jwijffels** [comment]
Thank you for making this faster. I'm not convinced however on the image_split. Currently image_connect combines blobs of pixels with the same intensity. Each blob gets assigned a number starting from 1 I think. but these numbers do not have a meaning whatsoever. They only indicate the identifier of the blob. Now image_split gives it the color of that meaningless number, while I think it should be better to represent it as black.

**Comment by jeroen** [comment]
Okay I thought it would be useful to keep the colors, so you can see how the image is composed. I also really liked how `image_flatten()` would then return the original image again. But maybe this should not be the default behavior then.

**Comment by jwijffels** [comment]
I think the default behaviour of keeping the colors is great and it completely makes sense that if you split the data by pixel level and the pixel levels are real colors, it's completely logical to retain the color.
So that makes complete sense if you quantized by color as in the example. 
But the imagemagick `connectedComponents` function returns just a number which identifies a blob, so it's not a real color, just an identifier, starting from 0 or 1 up to the number of blobs. And `autoLevel `just spreads out this identifier to the full color range otherwise you wouldn't see the blob. 
Maybe this can also be achieved with this type of change where the user can give in his own color in type or just 'black', just freewheeling here :

```
library(magick)
library(magick)
image_split <- function (image, type) 
{
  pixels <- as.integer(image)
  colors <- sort(unique(c(pixels)))
  blobs <- lapply(colors, function(col) {
    if(type == "colors"){
      image_read((pixels == col) * col)
    }else if(type == "black"){
      image_read((pixels == col) * -16777216L)
    }else{
      image_read((pixels == col) * type)
    }
  })
  image_join(blobs)
}
img <- demo_image("objects.gif") 
img %>% image_connect(connectivity = 8) %>% image_split(type = "black")
```

**Comment by jeroen** [comment]
Yes I was thinking of adding a parameter like that. Note that you can also easily drop the colors using something like `image_convert(type = 'bilevel')`

**Comment by jwijffels** [comment]
that suggestion also works nicely

**Comment by jeroen** [comment]
> I'm not sure if I understand that raster integer format and the range of it so I just put 16777216L here for black.

This is what R calls 'nativeraster'. The value of the integer has no meaning, it is actually a 32 bit `rgba` pixel that is stored in the memory of a 32 bit integer.

**Comment by jeroen** [comment]
I've added a `keep_color` parameter for now ....

**Comment by jwijffels** [comment]
That looks fine. Many thanks for all the efforts in implementing the changes!

**Comment by jeroen** [comment]
Cool. Do you have any other suggestions for features we could add?

**Comment by jwijffels** [comment]
Now that you are asking. Let's raise the bar a bit :)
Maybe something similar as https://github.com/aleju/imgaug for image augmentation and extending the wrapper around pjreddie darknet (for image segmentation/classification) which I had here: https://github.com/bnosac/image/tree/master/image.darknet but this is not related to imagemagick
I think a had a few other elements lying around somewhere but that was based on imagemagick 7

**Comment by jwijffels** [comment]
The following ones, I personally think are also relevant:
- boundingbox for a blob
- Image moments: Magick::Image::moments to get statistics of images
- affineTransform, I basically use this for showing how image matching works when comparing 2 images which are transformed

**Pull request closed without merging**
