### PR TITLE
Read NativeRasters

### LINKED ISSUE #37: Read nativeVector format images
I'm trying to plot an image directly to **magick** memory rather than round-tripping to disk, and can do so like so:

```
library(Cairo)
library(ggplot2)
library(magick)
x = 1680
y= 1050

Cairo(type="raster", width=x, height=y)
ggplot(mtcars, aes(x=cyl, y=mpg)) + geom_point()
i <- image_read(structure(packBits(intToBits(dev.capture(native=TRUE))), dim=c(4, x, y)))
dev.off()
image_write(i, "testmem.gif")
```

However, this is still slower than disk round-trip, with most of the time being taken up by translating the nativeRaster (8-bit ARGB, stored as integers) produced by `dev.capture()` to the right raw format:

screen shot 2016-12-06 at 8 52 56 pm

It would be great if `image_read()` could also take nativeRasters for this use case and do the right conversion in a performant way.  I think there are lots of applications where you'd like to manipulate plots without going to disk for good performance. (I'm currently trying to do this to update the **gganimate** package).

### PR DESCRIPTION
**Pull request by noamross**
This is the start of a PR.  I intend to do a few things before proposing merging.  Right now it closes #37 by implementing `magick_image_readbitmap_nativeraster()`, but not exporting it.  I think that the way to expose this function is a function called `image_capture()`, which should capture the contents of the graphics device to an image.

### CODE REVIEW

**Comment by noamross** [comment]
OK, let me know if you think this is merge-able.

**Comment by noamross** [comment]
An update: Now I read directly from the graphics device, rather than first pulling the nativeRaster into R.  This is nice and clean, and for devices that support it, includes transparency. The only problem is that raster capture is only supported for some devices, and font handling isn't as simple for those devices (Cairo package, X11, etc), as it is just using devices like `png()`.

**Comment by jeroenooms** [comment]
Thanks, I'll review this next time I work on magick, hopefully soon :)

**Comment by jeroen** [comment]
@noamross do you think this is still useful now that magick has it's own graphics device? See the [section on the graphics device](https://cran.r-project.org/web/packages/magick/vignettes/intro.html#drawing_and_graphics) in the vignette.

**Comment by noamross** [comment]
The device covers the main use cases I was considering, so I'm happy to close this.

**Comment by jeroen** [comment]
FYI I have added support for various raster times in `image_read()`but I want to encourage users to use the native magick graphics device rather than graphig with cairo and then dumping the raster.

**Pull request closed without merging**
