### PR TITLE
Initial add image_circle (proto/demo)

### PR DESCRIPTION
**Pull request by mikldk**
It possibly does not conform to the existing way things are done, but it should be possible to adapt.

### CODE REVIEW

**Comment by jeroenooms** [comment]
Thanks for this suggestion. However I am afraid exposing separate functions for each type of drawing will become bloated and complex soon. 

Ideal way would be if we could implement the drawing as an R graphics device so that the user can take advantage of R's native drawing functions.

**Comment by mikldk** [comment]
I see your point. I just didn't know that that direction was viable/possible.

**Comment by jeroenooms** [comment]
It is something I need to further investigate but I think it should be possible. 

The [svglite](https://cran.r-project.org/web/packages/svglite/index.html) package is a pretty neat example of how to implement a graphics device. We just need to investigate if R's graphic methods map to magick's drawing operations.

**Comment by mikldk** [comment]
That would be nice, but I have no experience with R graphics devices and so I have no clue how difficult it is to implement in practise. On the other hand, it's a quite good opportunity to learn some, though (but unfortunately I do not have the time right now).

**Comment by mikldk** [comment]
As you mentioned on Twitter, as.raster might take us some of the way:
`frink <- image_read("https://jeroenooms.github.io/images/frink.png")
par(pty = "s")
plot(NA, xlim = c(0, image_info(frink)$width), ylim = c(0, image_info(frink)$height), asp = 1)
rasterImage(frink, xleft = 0, xright = image_info(frink)$width, ybottom = 0, ytop = image_info(frink)$height)`

**Comment by mikldk** [comment]
Are you sure that you actually should implement a graphics device? Isn't it instead that you need to implement functions like [`rasterImage`](https://github.com/wch/r-source/blob/trunk/src/library/graphics/src/plot.c#L1816) and [`grid.raster`](https://github.com/wch/r-source/blob/trunk/src/library/grid/src/grid.c#L2888) but for `magick-image` instead of `raster`?

**Comment by jeroenooms** [comment]
What do you mean? Those `graphics::rasterImage` and `grid::grid.raster` are supported?

**Comment by mikldk** [comment]
Yes, but that requires `magick-image` to be converted to `raster` first which I guess is what should be avoided?

As I understand it, a new graphics device is (over-simplified) just a new output file format (or a variation that gives better files like `svglite`). We don't need that. We need `magick-image` to be put into `plot`s so that `points`, `lines` etc. work, right?

**Comment by jeroenooms** [comment]
But we can do that right:

```r
plot(cars)
rasterImage(frink, 21, 0, 25, 80)
symbols(10, 10, 5, inches = ".5", fg = "red", add = TRUE)
```

**Comment by mikldk** [comment]
Yes. But I thought the whole point was that you wanted to avoid converting to raster? Or is there a problem at all :)? Instead of my pull request (`image_circle`), you are right that I can simply do what you suggest (`raster` and `symbols`).

**Comment by jeroenooms** [comment]
Right so there are two approaches: 

 1. (currently possible) Convert `magick-image` to a raster, plot it on any graphics device and use standard R methods to print additional stuff to the graphics device.
 2. (not yet implemented) Keep the image in memory as a `magick-image` and use magick drawing methods to add lines and circles and stuff as you did for `image_circle`.

Now the thing I am suggesting is that instead of exporting `image_circle` and others directly to the user, we would instead expose a graphics device that calls these drawing methods internally when a user or package draws a circle on the graphics device.

So we would still implement something like `image_circle`, but instead of exporting it, we hook it up to [dd->circle](https://github.com/hadley/svglite/blob/master/src/devSVG.cpp#L610) callback from a graphics device.

This way users and packages can draw on a magick image using the standard drawing methods in R.

**Comment by mikldk** [comment]
I agree. But wouldn't that require the user to open the (yet-to-exist) new magick-device (writing to a file, e.g. `magick('image.png')`) before that would work? This would mean that the plot do not display in the Plot-window, but maybe e.g. in the View-windows like now. Would that we okay?

**Comment by jeroenooms** [comment]
Graphics devices are not limited to files. I think we could implement something like `magick(frink)` which would modify the `frink` image.

**Comment by jeroen** [comment]
Hi @mikldk, thanks for your contribution. I have decided to implement this using the new graphics device instead. See the [section in the vignette](https://cran.r-project.org/web/packages/magick/vignettes/intro.html#drawing_device) about drawing.

**Pull request closed without merging**
