### PR TITLE
Add optimize option to image_animate()

### PR DESCRIPTION
**Pull request by gaborcsardi**
Calls `OptimizeImageLayers()`.

### CODE REVIEW

**Comment by jeroen** [comment]
You're calling the C api now, but it may be easier to use the C++ STL Method optimizeImageLayers()

**Comment by gaborcsardi** [comment]
Oh, I completely missed that, I thought this was not included in the C++ API.... wait a minute....

**Comment by jeroen** [comment]
OK, will review tomorrow. Btw the C++ API in imagemagick is poorly documented, I usually just `grep` for the what I am looking for in `/usr/local/opt/imagemagick@6/include/ImageMagick-6/Magick++/`

**Comment by gaborcsardi** [comment]
OK, using the C++ API now. Thanks!

**Comment by gaborcsardi** [comment]
Actually, maybe instead of a separate function we could just have an `optimize` argument for `image_animate()`, because this function also converts everything to gif, anyway, and it does not make much sense to use it without creating an animation.

**Comment by gaborcsardi** [comment]
OK, I rewrote this as an `optimize` argument to `image_animate()`. I think this is much better.

**Comment by jeroen** [comment]
Great, I was doing to suggest this. I think it makes sense to make the default TRUE?

**Comment by gaborcsardi** [comment]
> I think it makes sense to make the default TRUE?

It takes much longer to optimize of course... I am using this for asciicast output, so it makes a huge difference there, because most of the screen stays the same, there is only a few new characters in a new frame. I expect that it also makes a big difference for scatterplots and similar.

FWIW for my use case I get much smaller output than with gifski, in perfect quality.

Anyway, I think I think `optimize = TRUE` might make sense, except that it'll make processing movie-like gifs (potentially much) slower.

**Comment by jeroen** [comment]
OK well if it's really slow maybe leave it the default. Things are already pretty slow as they are :)

**Pull request merged**
