### PR TITLE
C++ version of `as.raster.magick-image`

### PR DESCRIPTION
**Pull request by romainfrancois**
Because this comment was too tempting: 

```R
## apply is slow, can easily be optimized in c++.
```

This is just a serial C++ version. I get: 

```
> R <- old_as.raster(im)
> cpp <- as.raster(im)
> identical( R, cpp) 
[1] TRUE
> microbenchmark( cpp = as.raster(im), r = old_as.raster(im), times = 5 )
Unit: milliseconds
 expr        min         lq       mean     median         uq        max neval
  cpp   121.3381   121.6021   125.3086   123.7407   129.7754   130.0867     5
    r 11333.9366 11381.0601 11747.2822 11398.1421 12216.4571 12406.8148     5
```

### CODE REVIEW

**Comment by romainfrancois** [comment]
unfortunately it's not easy to make this parallel because  `out[k] = buf ;` eventually calls `mkString` which uses the global string cache ...

**Comment by jeroenooms** [comment]
Nice, thanks :)  I might at some point extract this and some other functions into a separate package, because there are other packages (besides magick) that do bitmap transformations.

**Comment by jeroenooms** [comment]
Squashed and merged in https://github.com/ropensci/magick/commit/327dfc38171f74225c7664c92b7110f6dae28333. Thanks!

**Comment by jeroenooms** [comment]
Euhh I think there is an indexing bug somewhere. The vignette now shows:

screen shot 2016-10-30 at 12 55 33 pm

**Comment by romainfrancois** [comment]
should be better now 😬

**Comment by jeroenooms** [comment]
Thanks.Squashed & merged in https://github.com/ropensci/magick/commit/b8d76d23b092d9f6df9251df9d278efbcfd0fc7a.

**Pull request closed without merging**
