### PR TITLE
Clarify the nature of the dither argument

### PR DESCRIPTION
**Pull request by Bisaloo**
Please let me know if you'd like me to run `devtools::document()`

### CODE REVIEW

**Comment by Bisaloo** [comment]
Additionally / alternatively, changing this line

```r
image_quantize <- function(image, max = 256, colorspace = 'rgb', dither = NULL, treedepth = NULL){
```

to 

```r
image_quantize <- function(image, max = 256, colorspace = 'rgb', dither = TRUE, treedepth = NULL){
```

to explicit this in the code would be really useful

**Comment by jeroen** [comment]
Sure you can change it. Yes please roxygenize.

**Comment by jeroen** [comment]
I think you need to roxygenize again to make the build pass.

**Comment by Bisaloo** [comment]
For a very strange reason, it doesn't update the `usage` section of `color.Rd`. I don't get any error message. I just doesn't do anything.

And if I update manually, it reverts back to `dither = NULL` in the Rd file when I roxygenize. I feel like I'm missing something obvious here.

**Pull request merged**
