### PR TITLE
Added black/white thresholding and combined it with image_lat in 1 function

### PR DESCRIPTION
**Pull request by jwijffels**

### CODE REVIEW

**Comment by jeroen** [comment]
Cool. There is also an STL method `thresholdImage(double x)`, is that the same as black/white?

**Comment by jwijffels** [comment]
I thought first that it was a combination of both but when I tried, it did not gave the expected results so I did not include it for the time being

**Comment by jeroen** [comment]
Thanks! I have modified it a bit and added support for channel based thresholding.

**Comment by jwijffels** [comment]
Looks great! Thanks for the fixes on the MagickLibVersion.

**Pull request merged**
