### PR TITLE
Implement defines for image_write

### LINKED ISSUE #258: Request: allow define for image_write
Sometimes I want to write an image with certain options defined. For example, from the command line, this will write a JPEG with a max size of 100kB:

```
convert input.jpg -define jpeg:extent=100kb output.jpg
```

It would be useful to be able to things like this with `image_write()`.

### PR DESCRIPTION
**Pull request by wch**
Closes #258.

A few things I'm unsure about:

* Unlike `magick_image_readbin`, which passes `Magick::readImages()` a `Magick::ReadOptions` object, this calls `defineValue()` on each `Magick::Image`. I think this is the right way to do it, but I'm not 100% sure.
* My understanding of the code is that defining the value mutates the `Image` object. However, when I try writing an image with `defines`, and then without it, the second time doesn't seem to keep those defined values. So maybe I'm probably not understanding it correctly.

Example:

```R
x <- image_read("https://jeroen.github.io/images/frink.png")
image_write(x, "frink.png")
image_write(x, "frink-big.png",
  defines = c(
    "png:compression-filter" = "1",
    "png:compression-level" = "0"
  )
)
image_write(x, "frink2.png")

file.info(c("frink.png", "frink-big.png", "frink2.png"))$size
#> [1]  67143 392512  67143
```

Also, this doesn't support defines where the key is defined without a value. The same is true for the current implementation in `image_read`, I believe. Here's an example from http://www.imagemagick.org/script/command-line-options.php#define, which defines two keys without values:

```
magick bilevel.tif -define ps:imagemask eps3:stencil.ps
```

### CODE REVIEW

**Comment by jeroen** [comment]
> My understanding of the code is that defining the value mutates the Image object. 

Yes that is correct, this is why we run `XPtrImage image = copy(input);` at the beginning of each function.

**Comment by jeroen** [comment]
@dlemstra two quick questions:
 1. Is it correct that write-options need to be set on the image object? (contrary to ReadOptions)?
 2.  How do we use `it->defineValue()` to set options without a value, such as `ps:imagemask` in the example above?

Thanks !

**Comment by wch** [comment]
For (2), I think you use `it->defineSet()` to set options without a value. We would need to decide on a good R API for those, though. I suppose `defines = c("ps:imagemask" = TRUE)` is might be OK.

https://imagemagick.org/api/Magick++/classMagick_1_1Image.html#a0834733f83262269f19e9a11a05f5566

Also, how would you feel about me adding an example for the use of `defines`, where it writes out a jpeg file that's limited to a specific size? That's the specific reason I wanted this feature, so I could post images to a forum running on ancient software which limits the image size to 100kB. Here's the Shiny app I made that does this (using this branch of magick):
https://winston.shinyapps.io/image_resizer/

**Comment by dlemstra** [comment]
1. Yes you will need to set the defines on the image. The `ReadOptions` are a helper for reading but you could also set the defines on the image.
2. There is no such option called `ps:imagemask`? Those defines need the value `true` as @wch suggested.
3. Yes they will always have a colon in them to define the context/coder.

**Comment by wch** [comment]
@dlemstra FWIW, I copied the `ps:imagemask` thing from here: http://www.imagemagick.org/script/command-line-options.php#define

**Comment by jeroen** [comment]
Notes for self: the imagemagick headers:

```c
    // Tagged image format define. Similar to the defineValue() method
    // except that passing the flag_ value 'true' creates a value-less
    // define with that format and key. Passing the flag_ value 'false'
    // removes any existing matching definition. The method returns 'true'
    // if a matching key exists, and 'false' if no matching key exists.
    void defineSet(const std::string &magick_,const std::string &key_,
      bool flag_);
    bool defineSet(const std::string &magick_,const std::string &key_) const;

    // Tagged image format define (set/access coder-specific option) The
    // magick_ option specifies the coder the define applies to.  The key_
    // option provides the key specific to that coder.  The value_ option
    // provides the value to set (if any). See the defineSet() method if the
    // key must be removed entirely.
    void defineValue(const std::string &magick_,const std::string &key_,
      const std::string &value_);
    std::string defineValue(const std::string &magick_,
      const std::string &key_) const;
```

Also the [defines list](https://legacy.imagemagick.org/script/defines.php) shows that there defines may also be used to control editing operations, in addition to encoders.

**Comment by wch** [comment]
I implemented this for both read and write, but it's probably not the right approach for read. For writes, you can use `x->defineValue()` or `x->defineSet()`. But for reading, I used `MagickCore::SetImageOption()` for both types, and it passes `"TRUE"` or `"FALSE"` as the value for the flags. (I'm aware that those will probably have to be converted to lower case.)

One thing that's unclear to me from the documentation: is there a difference between flags like `ps:imagemask`, which isn't followed by `=true` in the docs, and `tiff:ignore-layers`, which is followed by `=true` in the docs? Or is that just inconsistent documentation?

**Comment by jeroen** [comment]
Sorry for dropping the ball on this. I'll try to get this sorted today.

**Comment by wch** [comment]
Thanks! I forgot to mention this, but my implementation for booleans didn't work right, so I'm glad you went and did it yourself.

**Pull request closed without merging**
